In [2]:
import pandas as pd

In [3]:
df =pd.read_csv("make_hard_blend.csv")

In [14]:
def soft_voting(x):
 vars = {}
 for i in range(1,6):
  try:
   vars[x[f"model_{i}"]] += 1
  except:
   vars[x[f"model_{i}"]] = 1
 return max(vars, key=vars.get)

In [15]:
df["target_class"] = df.apply(soft_voting, axis=1)

In [18]:
df[["car_id","target_class"]].set_index("car_id").to_csv("submission.csv")

In [19]:


cat = pd.read_csv("votes/catboost_preds.csv")
lgbm = pd.read_csv("votes/lgbm_preds.csv")
xgb = pd.read_csv("votes/xgb_preds.csv")

In [26]:
ans = cat+lgbm+xgb

In [46]:
def voting(x:pd.Series):
 idx = x.index[x==max(x)]
 return "_".join(idx.item().split("_")[0:2])

In [48]:
ans["soft_preds"] = ans.apply(voting, axis=1)

In [50]:
ans[["soft_preds"]].to_csv("submission.csv")

In [51]:
df= pd.read_csv("meta_feautres_data.csv")

df

      index     target     model
0         0  65.927922  catboost
1         1  44.248116  catboost
2         2  43.807966  catboost
3         3  45.661121  catboost
4         4  43.653036  catboost
...     ...        ...       ...
1750    580  39.795555       xgb
1751    581  42.351254       xgb
1752    582  44.074200       xgb
1753    583  40.630420       xgb
1754    584  43.850530       xgb

[1755 rows x 3 columns]

In [ ]:
df = pd.pivot_table(df,
               index = "index",
               columns="model",
               values="target",
               ).reset_index()

In [73]:
df.columns = ["index","target_catboost", "target_lgbm", "target_xgb"]

In [74]:
for i in ["catboost", "lgbm", "xgb"]:
 for j in ["catboost", "lgbm", "xgb"]:
  df[f"{i}_dif_{j}"] = df[f"target_{i}"]-df[f"target_{j}"]
  df[f"{i}_div_{j}"] = df[f"target_{i}"]/df[f"target_{j}"]

In [75]:
df

,index,target_catboost,target_lgbm,target_xgb,catboost_dif_catboost,catboost_div_catboost,catboost_dif_lgbm,catboost_div_lgbm,catboost_dif_xgb,catboost_div_xgb,...,lgbm_dif_lgbm,lgbm_div_lgbm,lgbm_dif_xgb,lgbm_div_xgb,xgb_dif_catboost,xgb_div_catboost,xgb_dif_lgbm,xgb_div_lgbm,xgb_dif_xgb,xgb_div_xgb
0,0,65.927922,49.622930,55.741352,0.0,1.0,16.304993,1.328578,10.186570,1.182747,...,0.0,1.0,-6.118422,0.890235,-10.186570,0.845489,6.118422,1.123298,0.0,1.0
1,1,44.248116,43.244205,42.661655,0.0,1.0,1.003911,1.023215,1.586461,1.037187,...,0.0,1.0,0.582550,1.013655,-1.586461,0.964146,-0.582550,0.986529,0.0,1.0
2,2,43.807966,45.389293,42.217470,0.0,1.0,-1.581327,0.965161,1.590496,1.037674,...,0.0,1.0,3.171823,1.075131,-1.590496,0.963694,-3.171823,0.930120,0.0,1.0
3,3,45.661121,44.769051,40.969734,0.0,1.0,0.892070,1.019926,4.691387,1.114509,...,0.0,1.0,3.799317,1.092735,-4.691387,0.897256,-3.799317,0.915135,0.0,1.0
4,4,43.653036,40.462658,38.243040,0.0,1.0,3.190378,1.078847,5.409996,1.141464,...,0.0,1.0,2.219618,1.058040,-5.409996,0.876068,-2.219618,0.945144,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,580,43.372847,44.205443,39.795555,0.0,1.0,-0.832596,0.981165,3.577292,1.089892,...,0.0,1.0,4.409888,1.110814,-3.577292,0.917522,-4.409888,0.900241,0.0,1.0
581,581,44.168977,42.959736,42.351254,0.0,1.0,1.209241,1.028148,1.817723,1.042920,...,0.0,1.0,0.608482,1.014368,-1.817723,0.958846,-0.608482,0.985836,0.0,1.0
582,582,44.393186,43.844842,44.074200,0.0,1.0,0.548344,1.012506,0.318986,1.007237,...,0.0,1.0,-0.229358,0.994796,-0.318986,0.992815,0.229358,1.005231,0.0,1.0
583,583,43.649487,46.200331,40.630420,0.0,1.0,-2.550844,0.944787,3.019067,1.074306,...,0.0,1.0,5.569911,1.137087,-3.019067,0.930834,-5.569911,0.879440,0.0,1.0
584,584,44.128439,45.071626,43.850530,0.0,1.0,-0.943187,0.979074,0.277909,1.006338,...,0.0,1.0,1.221096,1.027847,-0.277909,0.993702,-1.221096,0.972908,0.0,1.0

In [76]:
df.set_index("index").to_csv("submission.csv")